export default function Colaboradores(){
    return`    
  
  <div class="home-img-colaboradores-container" style="margin: 5vw"> 
    <div class="home-img-colaboradores"> 

        <img class="home-img-colaboradores-redondo"
            src="./src/img/vivi.jpg"
            alt="Girl in a jacket"
        > 

        <img class="home-img-colaboradores-redondo"
            src="./src/img/alifer.jpg"
            alt="Girl in a jacket"
        > 

        <img class="home-img-colaboradores-redondo"
            src="./src/img/lest.jpg"
            alt="Girl in a jacket"
        > 

        <img class="home-img-colaboradores-redondo"
            src="./src/img/grazi.jpg"
            alt="Girl in a jacket"
        > 

        <img class="home-img-colaboradores-redondo"
            src="./src/img/marcos.jpg"
            alt="Girl in a jacket"
        > 

        <img class="home-img-colaboradores-redondo"
            src="./src/img/anna.jpg"
            alt="Girl in a jacket"
        > 

        <img class="home-img-colaboradores-redondo"
            src="./src/img/ester.jpg"
            alt="Girl in a jacket"
        > 

   </div>
   </div>
  
    
    `
}